### ISSUE TITLE
Show magic elements for Awakened only

### ISSUE THREAD

**Issue by gdelmee** [shadowfoundry/sr6-alpha-feedback#3]
Even the character has no magic:

![image](https://github.com/shadowfoundry/sr6-alpha-feedback/assets/17324443/b372740e-520c-4b60-9f8e-466dab82cc30)

it still shows the Magic attribute and the astral initiative:

![image](https://github.com/shadowfoundry/sr6-alpha-feedback/assets/17324443/0e12d651-77fb-4782-a1aa-d74f0ac5f142)

It could be great to show only those when the character needs it.

**Comment by deurk** [comment]
Moved to #alpha-sr6-feedback channel.
