### ISSUE TITLE
Attributes & associated are too long for the windows

### ISSUE THREAD

**Issue by gdelmee** [shadowfoundry/sr6-alpha-feedback#4]
The attributes & associated informations almost fit in the column:

![image](https://github.com/shadowfoundry/sr6-alpha-feedback/assets/17324443/905a090a-295e-44c5-b88f-46aca7632f61)

Incrising slightly the height of the windows could let it fit properly.

**Comment by karmaroms** [comment]
OS and web browser please, cause I don't have the same display.
<img width="205" alt="image" src="https://github.com/shadowfoundry/sr6-alpha-feedback/assets/77210927/c1ea89ab-b128-4fbc-a6d3-50975a9ead5e">

**Comment by gdelmee** [comment]
Yes, sorry.

Windows 10, Foundry client.

**Comment by gdelmee** [comment]
Same issue on Windows 10, with Edge Version 119.0.2151.72 (Version officielle) (64 bits)
![image](https://github.com/shadowfoundry/sr6-alpha-feedback/assets/17324443/cae28cb5-8ddf-43eb-96af-5d67f9784ae7)

**Comment by gdelmee** [comment]
Almost OK with kind of ugly scrolls on Windows 10 with Firefox 119.0.1 (64 bits)

![image](https://github.com/shadowfoundry/sr6-alpha-feedback/assets/17324443/e40cfde9-0222-4074-8931-6f6d74a37a86)

**Comment by gdelmee** [comment]
Switching to my 2736 x 1824 screen, Windows 10, with Edge Version 119.0.2151.72, it’s almost fine, I can still scroll a little:

![image](https://github.com/shadowfoundry/sr6-alpha-feedback/assets/17324443/3ad282a6-44fa-4bb0-bf0d-1723e6846d71)

![image](https://github.com/shadowfoundry/sr6-alpha-feedback/assets/17324443/0ebb15c9-9767-4d27-bdd0-53eab6167a15)

**Comment by deurk** [comment]
Moved to #alpha-sr6-feedback channel.
