### ISSUE TITLE
Firefox styling needs fixing

### ISSUE THREAD

**Issue by shadow-sedryk** [shadowfoundry/sr6-alpha-feedback#5]
Sur tous les champs s'affiche 2 flèches à la fin du champ. Parfois cela masque le texte.
![image](https://github.com/shadowfoundry/sr6-alpha-feedback/assets/151527482/3af5d434-2263-4ad0-bf02-560dd3e3f1c0)

![image](https://github.com/shadowfoundry/sr6-alpha-feedback/assets/151527482/d2f8ed3e-ec32-4f6c-8235-3781ba4f7fa0)

Ubuntu 22.04
Navigateur Firefox 119.0.1
compendium_0.0.0.1_alpha2
sr6_11.0.1-alpha2

**Comment by deurk** [comment]
Also, select fields are a mess under Firefox

![image](https://github.com/shadowfoundry/sr6-alpha-feedback/assets/498032/4ab79efd-8372-43d5-8441-747f4d27572f)

**Comment by deurk** [comment]
![IMG_20231121_095851](https://github.com/shadowfoundry/sr6-alpha-feedback/assets/498032/75fdb5bf-b12e-4c2f-99c8-b2349fb79393)

Nouveau petit problème sous Firefox. La barre empêche de supprimer ou d'ajouter une option

**Comment by deurk** [comment]
Moved to #alpha-sr6-feedback channel.
