### ISSUE TITLE
No direct way to reset damage monitor

### ISSUE THREAD

**Issue by gdelmee** [shadowfoundry/sr6-alpha-feedback#6]
Having damages registered in the monitors, in order to void those (rest for stun, healing for physical), there is no way to just void the monitor. We have to come back to 1 box, then click this one a second time to void it.

![Damage_monitor_no_reset](https://github.com/shadowfoundry/sr6-alpha-feedback/assets/17324443/835e87cf-6724-412b-8639-1ca6e5d2c6a3)

**Comment by deurk** [comment]
Right click on the monitor :)
