### ISSUE TITLE
Missing electrical damage in DV definition of weapon item

### ISSUE THREAD

**Issue by gdelmee** [shadowfoundry/sr6-alpha-feedback#7]
For the stun baton, there is no possibility to mark the electical damages from 5S(e).

![image](https://github.com/shadowfoundry/sr6-alpha-feedback/assets/17324443/f486b5d9-5773-4e17-b882-f7b1fab6ee9b)

**Comment by gdelmee** [comment]
Is it system.damage.element?

![image](https://github.com/shadowfoundry/sr6-alpha-feedback/assets/17324443/28c895d1-585e-4559-a66a-ebb7363eeaed)

If so, it is only missing in the UI.

**Comment by deurk** [comment]
Yup! Fixed in upcoming alpha.5
